/**
 * Scaffold logic for `/project init` — generates the baseline project files.
 *
 * Iron rule: NEVER overwrite. A target file is written only when it does not
 * already exist; anything present is reported as skipped and left untouched.
 *
 * Targets (relative to the project directory):
 *   .opencode/opencode.jsonc — project-level OpenCode config stub
 *   docs/git-commits.md      — conventional-commit convention for the repo
 *   AGENTS.md                — repo-level AI agent instructions stub
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs"
import { dirname } from "node:path"
import { resolveTarget, type ScaffoldTarget } from "./project-manager-config"

// ─── Templates ───────────────────────────────────────────────────────

const OPENCODE_CONFIG_TEMPLATE = `{
  "$schema": "https://opencode.ai/config.json"
  // Project-level OpenCode configuration — generated by /project init.
  // Docs: https://opencode.ai/docs/config/
  //
  // Plugin switches — unset fields fall back to the global config /
  // built-in defaults; uncomment to override for THIS project only
  // (remember the comma after $schema):
  //   "autoAdvisorMode": "lite"   off | lite | full — /auto-advisor <mode>
  //   "adrGuard": "on"            on | off          — /adr-guard <state>
  //   "adrGuardDir": "docs/adr"   ADR directory
}
`

const GIT_COMMITS_TEMPLATE = `# Git Commit Conventions

> Generated by \`/project init\` — edit freely, agents read this file.

This repository follows [Conventional Commits](https://www.conventionalcommits.org/).

## Format

\`\`\`
<type>(<optional scope>): <short summary>

<optional body — what and why, not how>

<optional footer — BREAKING CHANGE:, refs>
\`\`\`

## Types

| Type       | Meaning                                        |
| ---------- | ---------------------------------------------- |
| feat       | A new feature                                  |
| fix        | A bug fix                                      |
| refactor   | Code change that neither fixes nor adds a feature |
| docs       | Documentation only                             |
| test       | Adding or correcting tests                     |
| chore      | Build process, tooling, dependencies           |
| perf       | Performance improvement                        |
| ci         | CI configuration                               |

## Rules

- Summary line ≤ 72 characters, imperative mood ("add", not "added").
- \`feat\` / \`refactor\` commits should carry an ADR when a decision was made
  (see docs/adr/ when adr-guard is on).
- Breaking changes: \`!\` after the type/scope + \`BREAKING CHANGE:\` footer.
- One logical change per commit.

> Enforcement: while this file exists, the structural rules above (known
> commit type, \`type(scope): summary\` format, ≤72-char first line) are
> mechanically enforced at commit time — non-conforming messages are blocked.
> The rest of this document is guidance only.

## Examples

\`\`\`
feat(auth): add refresh-token rotation
fix(api): guard against nil session in logout handler
refactor!: drop legacy v1 endpoints

BREAKING CHANGE: /v1/* routes removed; migrate to /v2/*.
\`\`\`
`

const AGENTS_MD_TEMPLATE = `# AGENTS.md

> Generated by \`/project init\` — fill in the placeholders; AI coding agents
> read this file before working in the repository.

## Project Overview

<!-- One paragraph: what this project is and where the important code lives. -->

## Setup & Commands

\`\`\`sh
# install
# build
# test
# lint
\`\`\`

## Code Style

<!-- Naming, formatting, import order rules that agents must follow. -->

## Commit Convention

Follow docs/git-commits.md (Conventional Commits).

## Boundaries

- Never commit secrets or credentials.
- Do not modify CI configuration without explicit instruction.
`

const TEMPLATES: Record<ScaffoldTarget, string> = {
  ".opencode/opencode.jsonc": OPENCODE_CONFIG_TEMPLATE,
  "docs/git-commits.md": GIT_COMMITS_TEMPLATE,
  "AGENTS.md": AGENTS_MD_TEMPLATE,
}

// ─── Init ────────────────────────────────────────────────────────────

export type ScaffoldStatus = "created" | "skipped"

export interface ScaffoldResult {
  relPath: ScaffoldTarget
  status: ScaffoldStatus
}

/**
 * Run `/project init`: create each missing target file. Existing files are
 * skipped — never overwritten. Parent directories are created on demand.
 * Errors propagate to the caller (command hook reports them to the user).
 */
export function runInit(): ScaffoldResult[] {
  const results: ScaffoldResult[] = []
  for (const relPath of Object.keys(TEMPLATES) as ScaffoldTarget[]) {
    const absPath = resolveTarget(relPath)
    if (existsSync(absPath)) {
      results.push({ relPath, status: "skipped" })
      continue
    }
    mkdirSync(dirname(absPath), { recursive: true })
    writeFileSync(absPath, TEMPLATES[relPath], "utf-8")
    results.push({ relPath, status: "created" })
  }
  return results
}
