#requires -Version 5.1
<#
.SYNOPSIS
    Install/upgrade opencode config (~/.config/opencode) from this repo.

.DESCRIPTION
    - Generates a per-version file manifest under <repo>/install/versions/<version>.manifest.txt
      (auto-generated on install if missing).
    - On install: reads the target's .CONFIG_VERSION, deletes every file listed by
      THAT version's manifest, then overwrites the target with every file listed
      by the CURRENT manifest. Finally writes the new .CONFIG_VERSION.
    - Skipped paths (.git, node_modules, .metrics, install) are never shipped
      and never deleted from the target.

    Subcommands (positional, like install.sh):
      install     Apply current manifest to target (default).
      generate    Scan repo, write manifest (no install).
      status      Show installed version vs repo version, no changes.
      init        Backup target to a timestamped sibling, then clear it.
      uninstall   Remove the installed version's manifest files from the target.
      register    Install the global shim into ~/.local/bin.
      unregister  Remove the global shim from ~/.local/bin.

.PARAMETER Target
    Install target (defaults to ~/.config/opencode).

.PARAMETER Force
    Install even when installed version equals repo version.

.PARAMETER NoBackup
    Skip the backup step when running `init`.

.PARAMETER Yes
    Skip the confirmation prompt when running `init`.

.PARAMETER BinDir
    Directory for the global shim (defaults to ~/.local/bin; overrides
    $env:OPENCODE_BIN_DIR if both are set).

.EXAMPLE
    pwsh ./install/install.ps1                 # install (default)
    pwsh ./install/install.ps1 install -Force  # re-apply same version
    pwsh ./install/install.ps1 status          # show installed vs repo version
    pwsh ./install/install.ps1 generate        # generate manifest only
    pwsh ./install/install.ps1 init            # backup + clear target (fresh start)
    pwsh ./install/install.ps1 init -NoBackup  # clear without backup
    pwsh ./install/install.ps1 init -Yes       # skip confirmation prompt
    pwsh ./install/install.ps1 uninstall       # remove installed files (precise, manifest-driven)
    pwsh ./install/install.ps1 uninstall -Yes  # skip confirmation prompt
    pwsh ./install/install.ps1 register        # install global opencode-config command
    pwsh ./install/install.ps1 register -BinDir C:\Tools\bin
    pwsh ./install/install.ps1 unregister      # remove global command
    # Option switches (MCPs + external plugins): the repo's install/options.jsonc
    # is the single source of truth — every install applies it to the target.
    # It never ships to the target; edit it, then re-run install.

.NOTES
    Manifest format: one repo-relative path per line, forward slashes.
    Lines starting with # are comments. Trailing whitespace ignored.
#>

[CmdletBinding()]
param(
    [Alias('t')][string]$Target,
    [Alias('f')][switch]$Force,
    [switch]$NoBackup,
    [Alias('y')][switch]$Yes,
    [Alias('b')][string]$BinDir,
    [Alias('h')][switch]$Help,
    [Parameter(Position = 0, ValueFromRemainingArguments = $true)][string[]]$CommandArgs
)

$ErrorActionPreference = 'Stop'

# rtk decision from options.jsonc (Apply-Options overrides; $true = enabled)
$script:OptRtk = $true

# --- subcommand parse -------------------------------------------------------
# Positional subcommand (install / generate / status / init / uninstall),
# mirroring install.sh. Named params (-Target, -Force, -NoBackup, -Yes) are
# bound by PowerShell's parameter binder; everything else lands in $CommandArgs.
$Mode = 'Install'
if ($Help) {
    Get-Help $PSCommandPath -Detailed
    exit 0
}
if ($CommandArgs) {
    foreach ($token in $CommandArgs) {
        switch ($token) {
            'install'   { $Mode = 'Install' }
            'generate'  { $Mode = 'Generate' }
            'status'    { $Mode = 'Status' }
            'init'      { $Mode = 'Init' }
            'uninstall' { $Mode = 'Uninstall' }
            'register'  { $Mode = 'Register' }
            'unregister'{ $Mode = 'Unregister' }
            '--help'    { Get-Help $PSCommandPath -Detailed; exit 0 }
            default     { throw "unknown arg: $token" }
        }
    }
}

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
if (-not $Target) { $Target = Join-Path $HOME '.config/opencode' }
if (-not $BinDir) { $BinDir = if ($env:OPENCODE_BIN_DIR) { $env:OPENCODE_BIN_DIR } else { Join-Path $HOME '.local/bin' } }

# Global shim state.
$shimName   = 'opencode-config.ps1'
$shimSrc    = Join-Path $RepoRoot "bin/$shimName"
$shimSentinel = 'generated by opencode-config register'

# Whitelist the paths opencode actually reads at runtime — nothing else ships.
# providers/ ships as merge sources: install folds each providers/*.json into
# opencode.jsonc's `provider` node (see Merge-Providers). options.jsonc
# stays in install/ and NEVER ships to the target — Apply-Options reads it
# in place and applies its switches to opencode.jsonc.
$includePrefixes = @('agents/', 'commands/', 'plugins/', 'instructions/', 'opencode.jsonc', 'tui.json', 'tiers.json', 'profiles/', 'providers/', 'scripts/')
$excludePatterns = @('^scripts/pack\.', '^scripts/verify\.', '__pycache__', '\.pyc$', '\.tmp')
$markerRel = '.CONFIG_VERSION'  # active-version marker written into $Target (source is install/VERSION)

# rtk (https://github.com/rtk-ai/rtk) — CLI proxy that compresses command
# output before it reaches the LLM (60-90% smaller bash output). Install
# provisions it out of the box: if the binary is missing it's downloaded
# into ~/.local/bin (added to the user PATH when needed). The opencode
# integration ships in-tree as plugins/openrtk.ts (vendored openrtk) —
# no `rtk init` step; the official rtk.ts plugin is removed if present.
$RtkVersion = '0.45.0'
$RtkSha256  = '34cea9009a8099acdaf85147b971d95f65efabfa63fb3aea7d3e2b73e6f517c3'  # rtk-x86_64-pc-windows-msvc.zip

function Read-Version {
    # VERSION lives next to the script (install/VERSION); never inside $skipDirs scan,
    # never in the manifest — its content is shipped as $markerRel via Write-Marker instead
    $f = Join-Path $PSScriptRoot 'VERSION'
    if (-not (Test-Path $f)) {
        # fallback: short sha so the script never breaks for lack of a tag
        return (git -C $RepoRoot rev-parse --short HEAD 2>$null).Trim()
    }
    (Get-Content $f -TotalCount 1).Trim()
}

function Read-Manifest([string]$path) {
    if (-not (Test-Path $path)) { return @() }
    Get-Content $path |
        Where-Object { $_ -and $_ -notmatch '^\s*#' } |
        ForEach-Object { $_.Trim() -replace '\\', '/' } |
        Where-Object { $_ -ne '' }
}

function Read-Installed-Version {
    $f = Join-Path $Target $markerRel
    if (-not (Test-Path $f)) { return $null }
    (Get-Content $f -TotalCount 1).Trim()
}

function Write-Marker([string]$ver) {
    $f = Join-Path $Target $markerRel
    Set-Content -Path $f -Value $ver -Encoding UTF8 -NoNewline
}

function Test-PathContains([string]$dir) {
    $sep = [IO.Path]::PathSeparator
    $found = $false
    $env:PATH.Split($sep) | ForEach-Object { if ($_ -eq $dir) { $found = $true } }
    return $found
}

function Write-Shim([string]$dest) {
    $dir = Split-Path $dest -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    $lines = @(
        '# generated by opencode-config register — do not edit; rewritten on the next `register`.'
        "& `"$shimSrc`" @args"
    )
    $lines | Set-Content -Path $dest -Encoding UTF8
}

function Test-ShimOwned([string]$dest) {
    if (-not (Test-Path $dest)) { return $true }
    $head = (Get-Content -LiteralPath $dest -TotalCount 2) -join "`n"
    return $head -like "*$shimSentinel*"
}

# Provisions rtk out of the box: download the pinned release into
# ~/.local/bin when no rtk is on PATH (SHA256-verified, added to the user
# PATH when needed). The opencode hook is the vendored openrtk plugin
# (plugins/openrtk.ts, shipped with the config copy) — this function only
# removes a leftover official rtk.ts plugin so commands aren't rewritten
# twice. Any failure only warns — install itself never fails because of rtk.
function Ensure-Rtk([string]$dst) {
    if (-not $script:OptRtk) {
        # switched off in options.jsonc: the binary download is skipped AND
        # the vendored openrtk plugin leaves the target, so opencode no
        # longer rewrites commands through a (possibly absent) rtk
        Remove-Item -LiteralPath (Join-Path $dst 'plugins/openrtk.ts') -Force -ErrorAction SilentlyContinue
        Remove-Item -LiteralPath (Join-Path $dst 'plugins/openrtk') -Recurse -Force -ErrorAction SilentlyContinue
        Write-Host '[rtk] disabled (options.jsonc) — removed vendored openrtk plugin'
        return
    }
    try {
        $exe = (Get-Command rtk -ErrorAction SilentlyContinue).Source
        if (-not $exe) {
            # legacy location from the first 0.1.4 installer iteration
            $legacy = Join-Path $dst 'bin/rtk.exe'
            $homeBin = Join-Path $HOME '.local/bin'
            if (Test-Path $legacy) {
                if (-not (Test-Path $homeBin)) { New-Item -ItemType Directory -Path $homeBin -Force | Out-Null }
                Move-Item -LiteralPath $legacy -Destination (Join-Path $homeBin 'rtk.exe') -Force
                $exe = Join-Path $homeBin 'rtk.exe'
            } else {
                if ($env:PROCESSOR_ARCHITECTURE -ne 'AMD64') {
                    Write-Warning "[rtk] no prebuilt binary for $($env:PROCESSOR_ARCHITECTURE) — skipping"
                    return
                }
                $url = "https://github.com/rtk-ai/rtk/releases/download/v$RtkVersion/rtk-x86_64-pc-windows-msvc.zip"
                $tmpDir = Join-Path ([IO.Path]::GetTempPath()) ("rtk-" + [guid]::NewGuid().ToString('N'))
                $zip = "$tmpDir.zip"
                try {
                    Write-Host "[rtk] downloading rtk v$RtkVersion ..."
                    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
                    Invoke-WebRequest -Uri $url -OutFile $zip -UseBasicParsing
                    $hash = (Get-FileHash $zip -Algorithm SHA256).Hash.ToLowerInvariant()
                    if ($hash -ne $RtkSha256) {
                        throw "checksum mismatch: expected $RtkSha256, got $hash"
                    }
                    Expand-Archive -Path $zip -DestinationPath $tmpDir -Force
                    $extracted = Get-ChildItem $tmpDir -Recurse -Filter 'rtk.exe' | Select-Object -First 1
                    if (-not $extracted) { throw 'rtk.exe not found in archive' }
                    if (-not (Test-Path $homeBin)) { New-Item -ItemType Directory -Path $homeBin -Force | Out-Null }
                    Move-Item -LiteralPath $extracted.FullName -Destination (Join-Path $homeBin 'rtk.exe') -Force
                    $exe = Join-Path $homeBin 'rtk.exe'
                    Write-Host "[rtk] installed: $exe"
                } finally {
                    Remove-Item -LiteralPath $zip -Force -ErrorAction SilentlyContinue
                    Remove-Item -LiteralPath $tmpDir -Recurse -Force -ErrorAction SilentlyContinue
                }
            }
            if (-not (Test-PathContains $homeBin)) {
                [Environment]::SetEnvironmentVariable('Path', [Environment]::GetEnvironmentVariable('Path', 'User') + ";$homeBin", 'User')
                $env:PATH = "$env:PATH;$homeBin"   # make it visible to rtk init below
                Write-Host "[rtk] added $homeBin to user PATH (persistent; current shell updated)"
            }
        } else {
            Write-Host "[rtk] binary present: $exe"
        }
        # The opencode hook ships in-tree (plugins/openrtk.ts). Remove a
        # leftover official plugin from a previous `rtk init -g --opencode`
        # so tool.execute.before doesn't rewrite commands twice. Only files
        # carrying the official marker are touched — user code stays put.
        $rtkPlugin = Join-Path $dst 'plugins/rtk.ts'
        if (Test-Path $rtkPlugin) {
            $content = Get-Content $rtkPlugin -Raw
            if ($content -match 'RTK OpenCode plugin') {
                Remove-Item -LiteralPath $rtkPlugin -Force
                Write-Host '[rtk] removed official plugin plugins/rtk.ts (replaced by vendored openrtk)'
            }
        }
        # opt out of telemetry by default — users can re-enable with `rtk telemetry enable`.
        # Probe first: older builds (< ~0.40) have no telemetry subcommand and
        # would proxy `telemetry` as an external program (noisy error).
        $hasTelemetry = & $exe --help 2>&1 | Out-String
        if ($hasTelemetry -match '(?m)^\s*telemetry\b') {
            & $exe telemetry disable 2>&1 | ForEach-Object { Write-Host "[rtk] $_" }
        }
        # Suppress rtk's "No hook installed" banner. On Windows the bash
        # hook can never be installed (rtk init -g requires bash/jq/POSIX
        # perms), so the banner pollutes every command's stderr. rtk's
        # hook_check rate-limits via a marker file at
        # %LOCALAPPDATA%\rtk\.hook_warn_last — touching it silences the
        # warning for 24h; the vendored openrtk plugin refreshes it at
        # every opencode launch.
        $rtkDataDir = Join-Path $env:LOCALAPPDATA 'rtk'
        if (-not (Test-Path $rtkDataDir)) { New-Item -ItemType Directory -Path $rtkDataDir -Force | Out-Null }
        [IO.File]::WriteAllText((Join-Path $rtkDataDir '.hook_warn_last'), '')
    } catch {
        Write-Warning "[rtk] setup failed — continuing without rtk. Cause: $($_.Exception.Message)"
    }
}

# Auto-detects and adapts the Windows shell environment for OpenCode:
# Probes for Git Bash (bash.exe) and configures User $SHELL if not already set,
# allowing OpenCode's built-in `bash` tool to execute seamlessly on Windows.
function Ensure-ShellEnvironment {
    $existingShell = [System.Environment]::GetEnvironmentVariable('SHELL', 'User')
    if (-not $existingShell) {
        $existingShell = [System.Environment]::GetEnvironmentVariable('SHELL', 'Machine')
    }
    if ($existingShell -and (Test-Path $existingShell)) {
        Write-Host ("[shell] SHELL already configured: {0}" -f $existingShell)
        return
    }

    $candidates = @(
        'C:\Program Files\Git\bin\bash.exe',
        'C:\Program Files\Git\usr\bin\bash.exe',
        'C:\Program Files (x86)\Git\bin\bash.exe',
        'C:\Git\bin\bash.exe'
    )
    $foundBash = $null
    foreach ($cand in $candidates) {
        if (Test-Path $cand) {
            $foundBash = $cand
            break
        }
    }
    if (-not $foundBash) {
        $cmdBash = Get-Command 'bash' -ErrorAction SilentlyContinue
        if ($cmdBash -and $cmdBash.Source -and (Test-Path $cmdBash.Source) -and $cmdBash.Source -notmatch 'System32\\bash\.exe') {
            $foundBash = $cmdBash.Source
        }
    }

    if ($foundBash) {
        try {
            [System.Environment]::SetEnvironmentVariable('SHELL', $foundBash, [System.EnvironmentVariableTarget]::User)
            $env:SHELL = $foundBash
            Write-Host ("[shell] auto-configured User SHELL -> {0} (Git Bash detected)" -f $foundBash)
        } catch {
            Write-Warning ("[shell] failed to set User SHELL environment variable: $($_.Exception.Message)")
        }
    } else {
        Write-Host "[shell] Git Bash not found; OpenCode agents will operate in adaptive PowerShell mode."
    }
}

# Config-driven MCP CLI provisioning: walks opencode.jsonc's `mcp` block and
# runs each entry's `install` field when the entry is enabled and its CLI
# (command[0]) is missing from PATH. Adding a new MCP to the config is all it
# takes — no script changes. Idempotent (present → skip); disabled entries are
# skipped even if they pre-declare `install` (e.g. gitnexus — flipping
# enabled to true makes the next install provision it). Missing package
# managers or install failures only warn — opencode degrades to grep/glob.
# Like Ensure-Rtk, never fails the install itself.
function Ensure-Mcp([string]$dst) {
    $cfg = Join-Path $dst 'opencode.jsonc'
    if (-not (Test-Path $cfg)) { return }
    # Strip comment lines before parsing — ConvertFrom-Json tolerates most
    # JSONC, but whole-line // comments are the safe subset to strip.
    $lines = Get-Content $cfg | Where-Object { $_ -notmatch '^\s*//' }
    try { $obj = ($lines -join "`n") | ConvertFrom-Json }
    catch { Write-Warning "[mcp] cannot parse opencode.jsonc — skipping MCP provisioning. Cause: $($_.Exception.Message)"; return }
    if (-not $obj.mcp) { return }
    $failedMcps = [System.Collections.Generic.List[PSObject]]::new()
    foreach ($name in $obj.mcp.PSObject.Properties.Name) {
        $m = $obj.mcp.$name
        if (-not ($m.enabled)) { continue }
        $interpreters = @('node', 'bun', 'deno', 'python', 'python3', 'cmd', 'sh', 'bash', 'powershell', 'pwsh')
        $rawCli = if ($m.command -is [array] -and $m.command.Count -gt 0) { [string]$m.command[0] } elseif ($m.command) { [string]$m.command } else { $null }
        $cli = if ($interpreters -contains $rawCli -or -not $rawCli) { $name } else { $rawCli }
        if (-not $cli -or -not $m.install) { continue }
        if (Get-Command $cli -ErrorAction SilentlyContinue) {
            Write-Host "[mcp] $name already present"
            continue
        }
        Write-Host "[mcp] installing $name ($($m.install)) ..."
        try {
            # Check if command requires uv and auto-heal uv if missing
            $parts = ([string]$m.install) -split '\s+'
            if ($parts[0] -eq 'uv' -and -not (Get-Command 'uv' -ErrorAction SilentlyContinue)) {
                # Refresh PATH in case uv is in ~/.local/bin or ~/.cargo/bin
                $extraPaths = @(
                    (Join-Path $HOME '.local/bin'),
                    (Join-Path $HOME '.cargo/bin'),
                    (Join-Path $env:USERPROFILE '.local/bin'),
                    (Join-Path $env:USERPROFILE '.cargo/bin')
                )
                foreach ($ep in $extraPaths) {
                    if ((Test-Path $ep) -and -not ($env:PATH -split ';' -contains $ep)) {
                        $env:PATH = "$ep;$env:PATH"
                    }
                }
                if (-not (Get-Command 'uv' -ErrorAction SilentlyContinue)) {
                    Write-Host "[mcp] 'uv' not found; auto-installing uv via Astral installer ..."
                    try {
                        powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
                        foreach ($ep in $extraPaths) {
                            if ((Test-Path $ep) -and -not ($env:PATH -split ';' -contains $ep)) {
                                $env:PATH = "$ep;$env:PATH"
                            }
                        }
                    } catch {
                        Write-Warning "[mcp] failed to auto-install uv: $($_.Exception.Message)"
                    }
                }
            }

            if ($parts[0] -eq 'uv' -and -not (Get-Command 'uv' -ErrorAction SilentlyContinue)) {
                # Fallback to local python/pip if uv installation was unavailable
                $py = if (Get-Command 'python' -ErrorAction SilentlyContinue) { 'python' } elseif (Get-Command 'py' -ErrorAction SilentlyContinue) { 'py' } else { $null }
                if ($py) {
                    $pyVer = & $py --version 2>&1
                    Write-Host "[mcp] uv unavailable; falling back to detected Python environment: $py ($pyVer)"
                    if ($name -eq 'serena') {
                        & $py -m pip install --user --pre serena-agent
                    } else {
                        & $py -m pip install --user $name
                    }
                    if ($LASTEXITCODE -ne 0) {
                        throw "pip install exited with code $LASTEXITCODE"
                    }
                } else {
                    throw "neither 'uv' nor 'python' was found in PATH to install $name"
                }
            } else {
                # naive arg split — install commands in opencode.jsonc carry no quoted args
                & $parts[0] $parts[1..($parts.Count - 1)]
                if ($LASTEXITCODE -ne 0) {
                    throw "command '$($m.install)' exited with code $LASTEXITCODE"
                }
            }

            if (Get-Command $cli -ErrorAction SilentlyContinue) {
                Write-Host "[mcp] $name installed"
            } else {
                if (Get-Command 'uv' -ErrorAction SilentlyContinue) {
                    try { uv tool update-shell | Out-Null } catch {}
                }
                if (Get-Command $cli -ErrorAction SilentlyContinue) {
                    Write-Host "[mcp] $name installed (PATH updated)"
                } else {
                    $warnMsg = "[mcp] $name installed but '$cli' not on PATH yet — check its docs (e.g. 'uv tool update-shell'), then restart the terminal"
                    Write-Warning $warnMsg
                    $failedMcps.Add([pscustomobject]@{
                        Name = $name
                        Command = [string]$m.install
                        Error = "'$cli' is not on PATH after installation"
                    })
                }
            }
        } catch {
            $errDetail = $_.Exception.Message
            Write-Warning "[mcp] $name install failed: $errDetail"
            $failedMcps.Add([pscustomobject]@{
                Name = $name
                Command = [string]$m.install
                Error = $errDetail
            })
        }
    }
    if ($failedMcps.Count -gt 0) {
        Write-Host ''
        Write-Host "=================================================================" -ForegroundColor Red
        Write-Host " [!] MCP Installation Incomplete / Failed ($($failedMcps.Count) issue(s) detected):" -ForegroundColor Red
        foreach ($fm in $failedMcps) {
            Write-Host "   - $($fm.Name)" -ForegroundColor Yellow
            Write-Host "     Command : $($fm.Command)" -ForegroundColor Gray
            Write-Host "     Reason  : $($fm.Error)" -ForegroundColor DarkRed
        }
        Write-Host ""
        Write-Host " Next Steps:" -ForegroundColor Yellow
        Write-Host "   1. Try running the failed command(s) manually in your terminal." -ForegroundColor Gray
        Write-Host "   2. If you don't need a specific MCP, disable it in install/options.jsonc" -ForegroundColor Gray
        Write-Host "      or opencode.jsonc (set mcp.<name>.enabled = false)." -ForegroundColor Gray
        Write-Host "=================================================================" -ForegroundColor Red
        Write-Host ''
    }
}

# Pre-installs active npm plugins into OpenCode's native cache directory (~/.cache/opencode)
# using detected bun/npm/pnpm to eliminate startup latency. Never fails the installer.
function Ensure-Plugins([string]$dst) {
    $cfg = Join-Path $dst 'opencode.jsonc'
    if (-not (Test-Path $cfg)) { return }
    $obj = Read-JsoncFile $cfg
    if (-not $obj -or -not $obj.plugin) { return }

    $rawPlugins = @($obj.plugin | Where-Object { $_ -is [string] -and $_.Trim() -ne '' })
    if ($rawPlugins.Count -eq 0) { return }

    # Filter npm packages (ignore local file paths)
    $npmPlugins = @()
    foreach ($p in $rawPlugins) {
        $trimmed = $p.Trim()
        if ($trimmed -match '^(\.|\/|\\|file:|https?:)' -or $trimmed -match '\.(ts|js|mjs)$') { continue }
        $npmPlugins += $trimmed
    }
    if ($npmPlugins.Count -eq 0) { return }

    $cacheDir = Join-Path $HOME '.cache/opencode'
    $nodeModules = Join-Path $cacheDir 'node_modules'

    $missing = @()
    foreach ($p in $npmPlugins) {
        # Parse package directory name from specifier (strip version suffix)
        $pkgName = if ($p.StartsWith('@')) {
            $parts = $p.Substring(1) -split '@'
            '@' + $parts[0]
        } else {
            ($p -split '@')[0]
        }
        $pkgPath = Join-Path $nodeModules ($pkgName -replace '/', '\')
        if (-not (Test-Path $pkgPath)) {
            $missing += $p
        }
    }

    if ($missing.Count -eq 0) {
        Write-Host ("[plugin] all {0} active plugin(s) present in ~/.cache/opencode" -f $npmPlugins.Count)
        return
    }

    # Multi-tier package manager detection:
    # 1. Inspect existing lockfile in OpenCode cache directory
    $pm = $null
    if ((Test-Path (Join-Path $cacheDir 'bun.lock')) -or (Test-Path (Join-Path $cacheDir 'bun.lockb'))) {
        if (Get-Command 'bun' -ErrorAction SilentlyContinue) { $pm = 'bun' }
    } elseif (Test-Path (Join-Path $cacheDir 'package-lock.json')) {
        if (Get-Command 'npm' -ErrorAction SilentlyContinue) { $pm = 'npm' }
    } elseif (Test-Path (Join-Path $cacheDir 'pnpm-lock.yaml')) {
        if (Get-Command 'pnpm' -ErrorAction SilentlyContinue) { $pm = 'pnpm' }
    }

    # 2. Inspect the installation origin of the `opencode` binary (bun vs npm/node vs pnpm)
    if (-not $pm) {
        $opCmd = Get-Command 'opencode' -ErrorAction SilentlyContinue
        if ($opCmd) {
            $opPath = $opCmd.Source.ToLowerInvariant()
            if ($opPath -match '(\\|\/)bun(\\|\/)') {
                if (Get-Command 'bun' -ErrorAction SilentlyContinue) { $pm = 'bun' }
            } elseif ($opPath -match '(\\|\/)(npm|node|nvm|fnm|volta)(\\|\/)') {
                if (Get-Command 'npm' -ErrorAction SilentlyContinue) { $pm = 'npm' }
            } elseif ($opPath -match '(\\|\/)pnpm(\\|\/)') {
                if (Get-Command 'pnpm' -ErrorAction SilentlyContinue) { $pm = 'pnpm' }
            }
        }
    }

    # 3. Fallback to available tool in PATH (bun > npm > pnpm)
    if (-not $pm) {
        if (Get-Command 'bun' -ErrorAction SilentlyContinue) { $pm = 'bun' }
        elseif (Get-Command 'npm' -ErrorAction SilentlyContinue) { $pm = 'npm' }
        elseif (Get-Command 'pnpm' -ErrorAction SilentlyContinue) { $pm = 'pnpm' }
    }

    if (-not $pm) {
        Write-Host ("[plugin] bun/npm not found — {0} plugin(s) will be downloaded on first opencode launch" -f $missing.Count)
        return
    }

    if (-not (Test-Path $cacheDir)) {
        New-Item -ItemType Directory -Path $cacheDir -Force | Out-Null
    }
    $pkgJson = Join-Path $cacheDir 'package.json'
    if (-not (Test-Path $pkgJson)) {
        Set-Content -Path $pkgJson -Value '{"dependencies":{}}' -Encoding UTF8
    }

    Write-Host ("[plugin] pre-installing {0} plugin(s) via {1} into ~/.cache/opencode ..." -f $missing.Count, $pm)
    try {
        $origLoc = (Get-Location).Path
        Set-Location -LiteralPath $cacheDir
        try {
            if ($pm -eq 'bun') {
                & bun add $missing 2>&1 | Out-Null
            } elseif ($pm -eq 'npm') {
                & npm install --no-audit --no-fund $missing 2>&1 | Out-Null
            } elseif ($pm -eq 'pnpm') {
                & pnpm add $missing 2>&1 | Out-Null
            }
            if ($LASTEXITCODE -eq 0) {
                Write-Host ("[plugin] successfully pre-installed {0} plugin(s)" -f $missing.Count)
            } else {
                Write-Warning "[plugin] pre-install returned code $LASTEXITCODE — opencode will retry on launch"
            }
        } finally {
            Set-Location -LiteralPath $origLoc
        }
    } catch {
        Write-Warning "[plugin] pre-install error: $($_.Exception.Message)"
    }
}


function Generate-Manifest([string]$ver) {
    $outDir = Join-Path $RepoRoot 'install/versions'
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null
    $out = Join-Path $outDir "$ver.manifest.txt"
    $lines = @()
    Get-ChildItem -Path $RepoRoot -Recurse -File -Force | ForEach-Object {
        $rel = $_.FullName.Substring($RepoRoot.Length).TrimStart('\','/') -replace '\\','/'
        $include = $false
        foreach ($p in $includePrefixes) {
            if ($rel -eq $p.TrimEnd('/') -or $rel.StartsWith($p)) { $include = $true; break }
        }
        if ($include) {
            foreach ($ex in $excludePatterns) {
                if ($rel -match $ex) { $include = $false; break }
            }
        }
        if ($include) { $lines += $rel }
    }
    $lines | Sort-Object | Set-Content -Path $out -Encoding UTF8
    Write-Host ("wrote install/versions/{0}.manifest.txt ({1} files)" -f $ver, $lines.Count)
}

function Remove-ManifestFiles([string[]]$files, [string]$base, [string]$label) {
    if (-not $files -or $files.Count -eq 0) {
        Write-Host "[$label] no files to remove"
        return
    }
    foreach ($f in $files) {
        # Never delete the marker itself, even if a stale manifest listed it
        if ($f -eq $markerRel) { continue }
        $p = Join-Path $base $f
        if (Test-Path $p) {
            Remove-Item -LiteralPath $p -Recurse -Force
            Write-Host "[$label] rm $f"
        }
    }
}

function Copy-ManifestFiles([string[]]$files, [string]$from, [string]$to, [string]$label) {
    foreach ($f in $files) {
        $src = Join-Path $from $f
        $dst = Join-Path $to   $f
        if (-not (Test-Path $src)) {
            Write-Warning "[$label] missing source: $f"
            continue
        }
        $dstDir = Split-Path $dst -Parent
        if (-not (Test-Path $dstDir)) { New-Item -ItemType Directory -Path $dstDir -Force | Out-Null }
        Copy-Item -LiteralPath $src -Destination $dst -Recurse -Force
        Write-Host "[$label] cp $f"
    }
}

# Writes opencode.jsonc back to disk in repo style: pretty 2-space JSON, but
# every provider model entry stays on one line (mirrors providers/*.json and
# the hand-written opencode.jsonc). Plain ConvertTo-Json expands each model
# into ~15 lines. Trick: stringify model entries first, pretty-print, then
# unquote exactly those lines back into inline objects.
function Write-ConfigJson([string]$path, $obj) {
    # 1) stringify model entries so the pretty-printer keeps them intact
    if ($obj.provider) {
        foreach ($pn in $obj.provider.PSObject.Properties.Name) {
            $models = $obj.provider.$pn.models
            if (-not $models) { continue }
            foreach ($mn in $models.PSObject.Properties.Name) {
                $models.$mn = $models.$mn | ConvertTo-Json -Depth 10 -Compress
            }
        }
    }
    # 2) pretty-print, 3) strip the string wrapper off the stringified entries
    $text = $obj | ConvertTo-Json -Depth 20
    $text = [regex]::Replace($text, '(?m)^(\s*"[^"]+"\s*:\s*)"(\{\\".*\})"(,?)\s*$', {
        param($m)
        # unescape, then re-add the spaces the repo style uses ({ "name": "...", ... })
        $inner = $m.Groups[2].Value.Replace('\"', '"')
        $inner = $inner -replace ',"', ', "' -replace '":', '": ' -replace '\{', '{ ' -replace '\}', ' }'
        $m.Groups[1].Value + $inner + $m.Groups[3].Value
    })
    Set-Content -Path $path -Value $text -Encoding UTF8
}

function Read-JsoncFile([string]$path) {
    if (-not (Test-Path $path)) { return $null }
    try {
        $lines = Get-Content $path | Where-Object { $_ -notmatch '^\s*//' }
        return ($lines -join "`n") | ConvertFrom-Json
    } catch {
        return $null
    }
}

# Snapshots user profiles from ~/.config/opencode/profiles so custom or modified profiles survive reinstalls
function Read-ProfilesPreserve([string]$dst) {
    $pdir = Join-Path $dst 'profiles'
    if (-not (Test-Path $pdir)) { return @{} }
    $saved = @{}
    Get-ChildItem -Path $pdir -Filter '*.json' -File | ForEach-Object {
        try {
            $content = Get-Content $_.FullName -Raw
            $saved[$_.Name] = $content
        } catch { }
    }
    return $saved
}

# Restores custom or user-modified profile files over the freshly copied profiles/ directory
function Restore-ProfilesPreserve([string]$dst, [hashtable]$saved) {
    if (-not $saved -or $saved.Count -eq 0) { return 0 }
    $pdir = Join-Path $dst 'profiles'
    if (-not (Test-Path $pdir)) { New-Item -ItemType Directory -Path $pdir -Force | Out-Null }
    $restoredCount = 0
    foreach ($name in $saved.Keys) {
        $targetFile = Join-Path $pdir $name
        $prevContent = $saved[$name]
        if (-not (Test-Path $targetFile)) {
            Set-Content -Path $targetFile -Value $prevContent -Encoding UTF8
            $restoredCount++
        } else {
            $curContent = Get-Content $targetFile -Raw
            if ($curContent.Trim() -ne $prevContent.Trim()) {
                Set-Content -Path $targetFile -Value $prevContent -Encoding UTF8
                $restoredCount++
            }
        }
    }
    return $restoredCount
}

# Merges providers/*.json definitions into opencode.jsonc's `provider` node:
# extract the existing node, layer shipped definitions on top (repo wins per
# provider key — user-added providers we don't ship survive), overwrite-write.
# Runs BEFORE Restore-Preserve so preserved baseURL/apiKey still land on top
# of any {env:...} placeholders the shipped definitions carry.
function Merge-Providers([string]$dst) {
    $cfg = Join-Path $dst 'opencode.jsonc'
    $dir = Join-Path $dst 'providers'
    if (-not (Test-Path $cfg) -or -not (Test-Path $dir)) { return 0 }
    $defs = @(Get-ChildItem $dir -Filter '*.json' -File)
    if ($defs.Count -eq 0) { return 0 }
    $obj = Read-JsoncFile $cfg
    if (-not $obj) { return 0 }
    if (-not ($obj.PSObject.Properties.Name -contains 'provider')) {
        $obj | Add-Member -NotePropertyName 'provider' -NotePropertyValue ([pscustomobject]@{}) -Force
    }
    $count = 0
    foreach ($f in $defs) {
        try { $fileObj = Read-JsoncFile $f.FullName }
        catch { Write-Warning "[cur] skipping invalid provider file: providers/$($f.Name)"; continue }
        if (-not $fileObj) { continue }
        foreach ($pname in $fileObj.PSObject.Properties.Name) {
            $obj.provider | Add-Member -NotePropertyName $pname -NotePropertyValue $fileObj.$pname -Force
            $count++
        }
    }
    if ($count -gt 0) {
        Write-ConfigJson $cfg $obj
    }
    return $count
}

# Preserved across reinstalls: the two credential fields under provider.*.options,
# the whole provider.*.models map (deep-merged back: user-edited model entries
# — incl. custom model ids — win over the template, template-only models and
# fields still get in), the root `model`, and one model ref per tier (agents of
# a tier share one ref — same tier semantics as the /profile plugin).
# Everything else comes from the repo.
# Agent→tier mapping: agent-level `tier` fields are gone (opencode forwards
# unknown agent fields to the provider as model options — strict gateways
# reject them). The mapping now lives in tiers.json; snapshot reads the
# target's copy, falling back to the repo's for pre-migration targets.
$preserveJsonKeys = @('baseURL', 'apiKey')

function Read-TierMap([string]$dir) {
    # agent name → tier from <dir>/tiers.json; empty hashtable when missing
    $map = @{}
    $f = Join-Path $dir 'tiers.json'
    if (-not (Test-Path $f)) { return $map }
    try {
        $t = Read-JsoncFile $f
        if ($t) {
            foreach ($k in $t.PSObject.Properties.Name) {
                if ($k.StartsWith('$')) { continue }
                $map[$k] = [string]$t.$k
            }
        }
    } catch { }
    return $map
}

function Read-Preserve([string]$dst) {
    # returns hashtable of "provider.<name>.options.<key>" => value,
    # "provider.<name>.models" => models map, "model" => root model,
    # "tier.<name>" => tier model ref; or $null if no prior opencode.jsonc
    $f = Join-Path $dst 'opencode.jsonc'
    if (-not (Test-Path $f)) { return $null }
    try {
        $obj = Read-JsoncFile $f
        if (-not $obj) { return $null }
        $bag = @{}

        # Snapshot active profile if configured
        $actFile = Join-Path $dst '.active-profile'
        if (Test-Path $actFile) {
            $actName = (Get-Content $actFile -Raw).Trim()
            if ($actName) { $bag['.active-profile'] = $actName }
        }

        if ($obj.provider) {
            foreach ($pname in $obj.provider.PSObject.Properties.Name) {
                # custom model definitions (llm-router ids, added models, ...) —
                # snapshotted independently of the options block so providers
                # without credentials (auth-based, local routers) are covered too.
                # Deep-copied via JSON round-trip so the snapshot bag holds plain
                # values and the later merge can never mutate it through aliasing
                if ($obj.provider.$pname.models) {
                    $bag["provider.$pname.models"] = $obj.provider.$pname.models | ConvertTo-Json -Depth 10 | ConvertFrom-Json
                }
                $opts = $obj.provider.$pname.options
                if (-not $opts) { continue }
                foreach ($k in $preserveJsonKeys) {
                    if ($opts.PSObject.Properties.Name -contains $k) {
                        $bag["provider.$pname.options.$k"] = $opts.$k
                    }
                }
            }
        }
        # Root model + per-tier refs: first hit per tier wins (all agents of a
        # tier share one ref when managed via the /profile plugin). Tier of an
        # agent: legacy agent-level `tier` field first (pre-migration targets),
        # then the target's tiers.json, then the repo's tiers.json (covers
        # targets whose tier fields were already hand-removed).
        if ($obj.PSObject.Properties.Name -contains 'model' -and $obj.model) {
            $bag['model'] = [string]$obj.model
        }
        $tierMap = Read-TierMap $dst
        if ($tierMap.Count -eq 0) { $tierMap = Read-TierMap (Join-Path $PSScriptRoot '..') }
        if ($obj.agent) {
            foreach ($aname in $obj.agent.PSObject.Properties.Name) {
                $a = $obj.agent.$aname
                $t = if ($a.tier) { [string]$a.tier } elseif ($tierMap.ContainsKey($aname)) { $tierMap[$aname] } else { $null }
                if ($t -and $a.model -and -not $bag.ContainsKey("tier.$t")) {
                    $bag["tier.$t"] = [string]$a.model
                }
                if ($a.model) {
                    $bag["agent.$aname.model"] = [string]$a.model
                }
            }
        }
        return $bag
    } catch { return $null }
}

function Restore-Preserve([string]$dst, $bag) {
    if (-not $bag -or $bag.Count -eq 0) { return }
    $f = Join-Path $dst 'opencode.jsonc'
    $obj = Read-JsoncFile $f
    if (-not $obj) { return }

    # 1. Restore provider credentials and models
    foreach ($key in $bag.Keys) {
        if ($key -eq 'model') {
            # root model — tracks the user's default-tier choice
            if ($obj.PSObject.Properties.Name -contains 'model') {
                $obj.model = $bag[$key]
            } else {
                $obj | Add-Member -NotePropertyName 'model' -NotePropertyValue $bag[$key] -Force
            }
            continue
        }
        if ($key -like 'tier.*' -or $key -like 'agent.*' -or $key -eq '.active-profile') { continue }  # applied after provider restoration
        # NOTE: dotted-key match; -like would work too but regex keeps intent explicit
        if ($key -match '^provider\.[^.]+\.models$') {
            # deep-merge the user's model definitions over the shipped ones:
            # per-model the user's fields win (custom ids survive), models
            # only the template knows about stay in place
            $parts = $key -split '\.'
            $pname = $parts[1]
            if (-not $obj.provider) {
                $obj | Add-Member -NotePropertyName provider -NotePropertyValue ([pscustomobject]@{}) -Force
            }
            if (-not $obj.provider.$pname) {
                $obj.provider | Add-Member -NotePropertyName $pname -NotePropertyValue ([pscustomobject]@{}) -Force
            }
            $models = $obj.provider.$pname.models
            if (-not $models) {
                $obj.provider.$pname | Add-Member -NotePropertyName models -NotePropertyValue ([pscustomobject]@{}) -Force
                $models = $obj.provider.$pname.models
            }
            # NOTE: distinct loop vars — a reused $f here would shadow the
            # function's config-file path and Write-ConfigJson below would
            # write the merged result to a stray file instead of opencode.jsonc
            foreach ($modelKey in ($bag[$key]).PSObject.Properties.Name) {
                $um = $bag[$key].$modelKey
                if ($models.PSObject.Properties.Name -contains $modelKey) {
                    $target = $models.PSObject.Properties[$modelKey].Value
                    foreach ($fld in $um.PSObject.Properties.Name) {
                        if ($target.PSObject.Properties.Name -contains $fld) { $target.$fld = $um.$fld }
                        else { $target | Add-Member -NotePropertyName $fld -NotePropertyValue $um.$fld -Force }
                    }
                } else {
                    $models | Add-Member -NotePropertyName $modelKey -NotePropertyValue $um -Force
                }
            }
            continue
        }
        # dotted path: provider.<name>.options.<field>
        $parts = $key -split '\.'
        if ($parts.Count -ne 4 -or $parts[0] -ne 'provider' -or $parts[2] -ne 'options') { continue }
        $pname = $parts[1]; $field = $parts[3]
        if (-not $obj.provider) {
            $obj | Add-Member -NotePropertyName provider -NotePropertyValue ([pscustomobject]@{}) -Force
        }
        if (-not $obj.provider.$pname) {
            # Bag references a provider that's missing after the copy step
            # (e.g. user added a custom provider we don't ship). Re-create it so the user's
            # credentials aren't silently dropped — the next reinstall will hit the same path.
            $obj.provider | Add-Member -NotePropertyName $pname -NotePropertyValue ([pscustomobject]@{}) -Force
        }
        $opts = $obj.provider.$pname.options
        if (-not $opts) {
            $obj.provider.$pname | Add-Member -NotePropertyName options -NotePropertyValue ([pscustomobject]@{}) -Force
            $opts = $obj.provider.$pname.options
        }
        if ($opts.PSObject.Properties.Name -contains $field) {
            $opts.$field = $bag[$key]
        } else {
            $opts | Add-Member -NotePropertyName $field -NotePropertyValue $bag[$key] -Force
        }
    }

    # 2. Replay active profile baseline if present
    $tierMap = Read-TierMap $dst
    $actProfileName = $bag['.active-profile']
    if ($actProfileName) {
        $profFile = Join-Path $dst "profiles/$actProfileName.json"
        if (Test-Path $profFile) {
            try {
                $profObj = Read-JsoncFile $profFile
                if ($profObj -and $profObj.tiers) {
                    if ($profObj.tiers.default) {
                        $obj.model = [string]$profObj.tiers.default
                    }
                    if ($obj.agent -and $tierMap.Count -gt 0) {
                        foreach ($tName in $profObj.tiers.PSObject.Properties.Name) {
                            $tRef = [string]$profObj.tiers.$tName
                            foreach ($an in $obj.agent.PSObject.Properties.Name) {
                                if ($tierMap.ContainsKey($an) -and $tierMap[$an] -eq $tName) {
                                    $obj.agent.$an.model = $tRef
                                }
                            }
                        }
                    }
                }
            } catch { }
        }
    }

    # 3. Tier refs: rewrite every agent of the tier in lockstep (same semantics as
    # the /profile plugin's apply) — also covers agents a newer template added.
    # Agent→tier comes from the freshly copied target tiers.json.
    if ($obj.agent -and $tierMap.Count -gt 0) {
        foreach ($key in $bag.Keys) {
            if ($key -notlike 'tier.*') { continue }
            $tier = $key -replace '^tier\.', ''
            $ref = $bag[$key]
            foreach ($agentName in $obj.agent.PSObject.Properties.Name) {
                if ($tierMap.ContainsKey($agentName) -and $tierMap[$agentName] -eq $tier) { $obj.agent.$agentName.model = $ref }
            }
        }
    }

    # 4. Direct agent model picks: restore agent-specific overrides
    if ($obj.agent) {
        foreach ($key in $bag.Keys) {
            if ($key -notlike 'agent.*.model') { continue }
            $parts = $key -split '\.'
            $aname = $parts[1]
            if ($obj.agent.PSObject.Properties.Name -contains $aname) {
                $obj.agent.$aname.model = [string]$bag[$key]
            }
        }
    }

    Write-ConfigJson $f $obj
}

# Applies the repo's install/options.jsonc — the single source of truth for
# which MCPs and external plugins are active, plus the default agent — onto
# the target opencode.jsonc:
#   mcp.<name>    -> mcp.<name>.enabled
#   plugin.<name> -> membership in the `plugin` array
#   default_agent -> root `default_agent` (validated against the `agent`
#                    block; unknown names are rejected, template value kept)
# The file is read IN PLACE from install/ and overwrites the target state on
# EVERY install — nothing is copied to the target, so there is no installed
# copy that could be mistaken for an editable config (user choices persist
# in the repo file itself, which the install runs from). Entries the options
# file doesn't list keep the shipped opencode.jsonc value; entries the
# target carries but the options file doesn't know survive as-is (user
# additions). Runs AFTER Restore-Preserve (options.jsonc wins over any
# preserved opencode.jsonc flags); Ensure-Mcp afterwards provisions newly
# enabled CLIs.
function Apply-Options([string]$dst) {
    $compFile = Join-Path $PSScriptRoot 'options.jsonc'
    $cfg = Join-Path $dst 'opencode.jsonc'
    if (-not (Test-Path $compFile) -or -not (Test-Path $cfg)) { return }
    $lines = Get-Content $compFile | Where-Object { $_ -notmatch '^\s*//' }
    try { $comp = ($lines -join "`n") | ConvertFrom-Json }
    catch { Write-Warning "[options] cannot parse options.jsonc — skipping. Cause: $($_.Exception.Message)"; return }
    if (-not $comp.mcp)    { $comp | Add-Member -NotePropertyName 'mcp' -NotePropertyValue ([pscustomobject]@{}) -Force }
    if (-not $comp.plugin) { $comp | Add-Member -NotePropertyName 'plugin' -NotePropertyValue ([pscustomobject]@{}) -Force }
    # apply onto opencode.jsonc
    $cfgLines = Get-Content $cfg | Where-Object { $_ -notmatch '^\s*//' }
    try { $obj = ($cfgLines -join "`n") | ConvertFrom-Json }
    catch { Write-Warning "[options] cannot parse opencode.jsonc — skipping. Cause: $($_.Exception.Message)"; return }
    if ($obj.mcp) {
        foreach ($n in $obj.mcp.PSObject.Properties.Name) {
            # only entries the options file lists get their flag forced;
            # unlisted ones keep the shipped opencode.jsonc value
            if ($comp.mcp.PSObject.Properties.Name -contains $n) { $obj.mcp.$n.enabled = [bool]$comp.mcp.$n }
        }
    }
    # plugin array: drop disabled, add enabled-but-missing, keep unknown
    $existing = @(); if ($obj.plugin) { $existing = @($obj.plugin) }
    $keptNames = @($comp.plugin.PSObject.Properties.Name)
    $kept = @($existing | Where-Object { ($keptNames -notcontains $_) -or [bool]$comp.plugin.$_ })
    foreach ($n in $keptNames) {
        if ([bool]$comp.plugin.$n -and $kept -notcontains $n) { $kept += $n }
    }
    if ($obj.PSObject.Properties.Name -contains 'plugin') { $obj.plugin = @($kept) }
    else { $obj | Add-Member -NotePropertyName 'plugin' -NotePropertyValue @($kept) -Force }
    # default_agent: forced onto the root field, but only when it names an
    # agent that actually exists in the shipped `agent` block — a typo
    # here would leave opencode without an entry agent, so unknown names
    # are rejected with a warning (template value kept)
    $optAgent = ''
    if ($comp.PSObject.Properties.Name -contains 'default_agent' -and $comp.default_agent -is [string] -and $comp.default_agent) {
        $optAgent = [string]$comp.default_agent
        if ($obj.agent -and $obj.agent.PSObject.Properties.Name -contains $optAgent) {
            if ($obj.PSObject.Properties.Name -contains 'default_agent') {
                $obj.default_agent = $optAgent
            } else {
                $obj | Add-Member -NotePropertyName 'default_agent' -NotePropertyValue $optAgent -Force
            }
        } else {
            Write-Warning "[options] default_agent '$optAgent' not found in the agent block — keeping '$($obj.default_agent)'"
            $optAgent = [string]$obj.default_agent   # report what actually stays
        }
    } else {
        $optAgent = [string]$obj.default_agent   # not listed: keep the shipped value
    }
    Write-ConfigJson $cfg $obj
    # export the rtk decision for Ensure-Rtk (runs right after this)
    $script:OptRtk = if ($comp.PSObject.Properties.Name -contains 'rtk') { [bool]$comp.rtk } else { $true }
    $mProps = @($comp.mcp.PSObject.Properties)
    $pProps = @($comp.plugin.PSObject.Properties)
    $mOn = @($mProps | Where-Object { [bool]$_.Value }).Count
    $pOn = @($pProps | Where-Object { [bool]$_.Value }).Count
    Write-Host ("[options] applied options.jsonc (mcp: {0} on / {1} off; plugins: {2} on / {3} off; rtk: {4}; default_agent: {5})" -f $mOn, ($mProps.Count - $mOn), $pOn, ($pProps.Count - $pOn), $(if ($script:OptRtk) { 'on' } else { 'off' }), $optAgent)
}

$ver     = Read-Version
$instDir = Join-Path $RepoRoot 'install/versions'
$curMan  = Join-Path $instDir "$ver.manifest.txt"

switch ($Mode) {
    'Register' {
        if (-not (Test-Path $shimSrc)) {
            throw "missing: $shimSrc — this repo is incomplete, expected bin/opencode-config.ps1"
        }
        $dest = Join-Path $BinDir $shimName
        if (-not (Test-ShimOwned $dest)) {
            throw "refusing to overwrite existing file at $dest (not our shim); remove it manually, or pass -BinDir to choose a different location"
        }
        Write-Shim $dest
        Write-Host "registered: $dest"
        Write-Host "           -> $shimSrc"
        if (-not (Test-PathContains $BinDir)) {
            Write-Host ''
            Write-Host "NOTE: $BinDir is not on PATH."
            Write-Host "  [Environment]::SetEnvironmentVariable('Path', `$env:Path + ';$BinDir', 'User')"
        }
    }
    'Unregister' {
        $dest = Join-Path $BinDir $shimName
        if (-not (Test-Path $dest)) {
            Write-Host "not registered at $dest (nothing to do)"
            return
        }
        if (-not (Test-ShimOwned $dest)) {
            throw "refusing to remove $dest (does not look like an opencode-config shim)"
        }
        Remove-Item -LiteralPath $dest -Force
        Write-Host "unregistered: $dest"
    }
    'Init' {
        # Backup the entire target directory to a timestamped sibling, then clear it.
        # Designed for a fresh start: after init, run `install` to reinstall
        # the config files; credentials are then configured inside opencode.
        if (-not (Test-Path $Target)) {
            Write-Host "target directory does not exist: $Target"
            Write-Host 'nothing to do'
            return
        }
        $items = @(Get-ChildItem $Target -Force)
        if ($items.Count -eq 0) {
            Write-Host "target directory is already empty: $Target"
            return
        }

        # Timestamped backup as a sibling directory.
        $timestamp = (Get-Date -Format 'yyyyMMdd-HHmmss')
        $backupDir = "${Target}.backup.${timestamp}"

        if (-not $NoBackup) {
            Copy-Item $Target $backupDir -Recurse -Force
            $backupCount = @(Get-ChildItem $backupDir -Recurse -Force).Count
            Write-Host ("backed up {0} item(s) to: {1}" -f $backupCount, $backupDir)
        } else {
            Write-Host 'skipping backup (-NoBackup)'
        }

        # Confirmation before destructive operation.
        if (-not $Yes) {
            $confirm = Read-Host "clear all files in $Target? (y/N)"
            if ($confirm -ne 'y' -and $confirm -ne 'Y') {
                Write-Host 'cancelled'
                return
            }
        }

        # Clear everything in the target directory (keep the directory itself).
        foreach ($item in $items) {
            Remove-Item $item.FullName -Recurse -Force
        }
        Write-Host ("cleared {0} ({1} item(s) removed)" -f $Target, $items.Count)
        Write-Host ''
        Write-Host 'next steps:'
        Write-Host '  pwsh install/install.ps1 install   # reinstall config files'
    }
    'Uninstall' {
        # Reverse of install: read the target's marker, delete exactly the
        # files that version's manifest lists (user-added files survive),
        # then drop the installer-owned extras (options.jsonc, marker, stale
        # marker backup). Refuses to guess when the manifest is missing.
        $installed = Read-Installed-Version
        if (-not $installed) {
            Write-Host "nothing installed at $Target (no $markerRel)"
            return
        }
        $prevMan = Join-Path $instDir "$installed.manifest.txt"
        if (-not (Test-Path $prevMan)) {
            throw "manifest missing: install/versions/$installed.manifest.txt — cannot uninstall precisely. Use 'init' to back up and clear the target instead."
        }
        $prevFiles = Read-Manifest $prevMan
        Write-Host ("installed: {0} ({1} manifest file(s))" -f $installed, $prevFiles.Count)
        if (-not $Yes) {
            $confirm = Read-Host "remove these files from $Target? (y/N)"
            if ($confirm -ne 'y' -and $confirm -ne 'Y') {
                Write-Host 'cancelled'
                return
            }
        }
        Remove-ManifestFiles $prevFiles $Target "uninstall"
        # Installer-owned extras that never live in the manifest (the
        # options.jsonc copy is a leftover of older installers — install
        # no longer ships it)
        foreach ($extra in @('options.jsonc', $markerRel, "$markerRel.bak")) {
            $p = Join-Path $Target $extra
            if (Test-Path $p) {
                Remove-Item -LiteralPath $p -Force
                Write-Host "[uninstall] rm $extra"
            }
        }
        # Prune directories the manifest shipped: deepest first, only when
        # empty — any user-added content keeps its folder alive. Repeated
        # passes until nothing new empties out (a parent only becomes empty
        # once its last emptied child is gone).
        $dirs = @($prevFiles) | ForEach-Object { Split-Path (Join-Path $Target ($_ -replace '/', '\')) -Parent }
        # dedupe on the full path FIRST — Sort-Object -Unique with a script
        # block compares the property (Length), which silently drops equal-
        # length siblings like plugins/project-manager vs plugins/review-fix-loop
        $dirs = @($dirs | Where-Object { $_ -and $_ -ne $Target } | Sort-Object -Unique | Sort-Object { $_.Length } -Descending)
        do {
            $pruned = 0
            foreach ($d in $dirs) {
                if ((Test-Path $d) -and @(Get-ChildItem $d -Force).Count -eq 0) {
                    Remove-Item -LiteralPath $d -Force
                    Write-Host "[uninstall] rmdir $($d.Substring($Target.Length).TrimStart('\','/'))"
                    $pruned++
                }
            }
        } while ($pruned -gt 0)
        Write-Host "uninstalled $installed"
        Write-Host ''
        Write-Host 'notes:'
        Write-Host '  - files you added yourself were left in place; `init` clears everything'
        Write-Host '  - the rtk binary + MCP CLIs are external tools and stay installed'
        Write-Host '  - `unregister` removes the global opencode-config shim'
    }
    'Generate' {
        if (Test-Path $curMan) {
            throw "install/versions/$ver.manifest.txt already exists; remove it first to regenerate"
        }
        Generate-Manifest $ver
    }
    'Status' {
        $installed = Read-Installed-Version
        Write-Host ("installed: {0}" -f ($(if ($installed) { $installed } else { '(none)' })))
        Write-Host ("repo:      {0}" -f $ver)
        Write-Host ("manifest:  install/versions/{0}.manifest.txt ({1})" -f $ver, $(if (Test-Path $curMan) { 'present' } else { 'will auto-generate on next install' }))
    }
    'Install' {
        if (-not (Test-Path $curMan)) {
            Write-Host ("install/versions/{0}.manifest.txt missing, generating..." -f $ver)
            Generate-Manifest $ver
        }
        $installed = Read-Installed-Version
        if ($installed -eq $ver -and -not $Force) {
            Write-Host "already at $ver, nothing to do (-Force to reapply)"
            return
        }
        if (-not (Test-Path $Target)) { New-Item -ItemType Directory -Path $Target -Force | Out-Null }

        # Snapshot the existing marker before any destructive work so a partial
        # failure leaves the target referencing the version that's actually still on disk
        $prevMarkerBackup = $null
        if ($installed) {
            $prevMarkerBackup = Join-Path $Target ($markerRel + '.bak')
            Copy-Item -LiteralPath (Join-Path $Target $markerRel) -Destination $prevMarkerBackup -Force
        }

        try {
            # Snapshot user state in opencode.jsonc and profiles/ BEFORE anything gets removed —
            # step 1 deletes it as part of the previous manifest
            $preserve = Read-Preserve $Target
            $savedProfiles = Read-ProfilesPreserve $Target

            # 1) remove files listed by previous version's manifest
            if ($installed) {
                $prevMan = Join-Path $instDir "$installed.manifest.txt"
                $prevFiles = Read-Manifest $prevMan
                Write-Host ("[prev: {0}] removing {1} files" -f $installed, $prevFiles.Count)
                Remove-ManifestFiles $prevFiles $Target "prev"
            } else {
                Write-Host "[prev: none] skipping removal"
            }

            # 2) copy current manifest over target (preserve credentials + model picks in opencode.jsonc)
            $curFiles = Read-Manifest $curMan
            Write-Host ("[cur: {0}] copying {1} files" -f $ver, $curFiles.Count)
            Copy-ManifestFiles $curFiles $RepoRoot $Target "cur"

            # Restore custom or modified profile files
            if ($savedProfiles -and $savedProfiles.Count -gt 0) {
                $restoredProfCount = Restore-ProfilesPreserve $Target $savedProfiles
                if ($restoredProfCount -gt 0) {
                    Write-Host ("[cur: {0}] restored {1} custom/modified profile(s) in profiles/" -f $ver, $restoredProfCount)
                }
            }

            # Fold shipped providers/*.json into the `provider` node before the
            # preserve-restore, so user credentials override {env:...} placeholders
            $merged = Merge-Providers $Target
            if ($merged -gt 0) {
                Write-Host ("[cur: {0}] merged {1} provider(s) from providers/ into opencode.jsonc" -f $ver, $merged)
            }

            # options.jsonc never ships to the target — Apply-Options reads
            # the repo file in place. Older installers left a copy behind;
            # delete it so nobody mistakes it for an editable config
            Remove-Item -LiteralPath (Join-Path $Target 'options.jsonc') -Force -ErrorAction SilentlyContinue

            if ($preserve) {
                Restore-Preserve $Target $preserve
                # models entries count per model, not per provider, so the
                # message reflects the actual number of restored fields
                $kept = 0
                foreach ($k in $preserve.Keys) {
                    if ($k -match '^provider\.[^.]+\.models$') { $kept += ($preserve[$k]).PSObject.Properties.Name.Count }
                    else { $kept++ }
                }
                Write-Host ("[cur: {0}] preserved {1} field(s) (credentials + models + model definitions) in opencode.jsonc" -f $ver, $kept)
            }

            # options.jsonc decides which MCPs/plugins are active — the repo
            # file overwrites the target unconditionally (overrides preserved
            # state; Ensure-Mcp below provisions newly enabled entries)
            Apply-Options $Target

            # Provision rtk binary + clean up the official plugin (warns, never fails)
            Ensure-Rtk $Target

            # Provision MCP CLIs for the `mcp` block (warns, never fails)
            Ensure-Mcp $Target

            # Pre-install active npm plugins into OpenCode cache (~/.cache/opencode)
            Ensure-Plugins $Target

            # Auto-adapt and configure Windows shell environment (Git Bash / SHELL)
            Ensure-ShellEnvironment

            # 3) marker goes last — only success reaches here
            Write-Marker $ver
            Write-Host "installed $ver"
        } catch {
            # restore the old marker so the next run can reconcile against the version still on disk
            if ($prevMarkerBackup -and (Test-Path $prevMarkerBackup)) {
                Copy-Item -LiteralPath $prevMarkerBackup -Destination (Join-Path $Target $markerRel) -Force
                Remove-Item -LiteralPath $prevMarkerBackup -Force
                Write-Error ("install failed; restored marker to $installed. Cause: $($_.Exception.Message)")
            } else {
                Write-Error ("install failed; target may be in a partial state. Re-run with -Force. Cause: $($_.Exception.Message)")
            }
            throw
        }
        if ($prevMarkerBackup -and (Test-Path $prevMarkerBackup)) {
            Remove-Item -LiteralPath $prevMarkerBackup -Force
        }
    }
}